# 01 — Collect SEC 10-K Filings

This notebook downloads 10-K filings for five companies (AAPL, MSFT, NVDA, TSLA, JPM) across fiscal years 2022–2024 directly from the SEC EDGAR REST API.

**What it does:**
1. Queries `https://data.sec.gov/submissions/CIK{cik}.json` for each company to find accession numbers
2. Downloads the primary filing document, strips HTML, saves as plain text
3. Writes `data/processed/filing_metadata.csv` with provenance for all downloads

**Expected output:** 15 `.txt` files in `data/raw/`, one per company-year combination.

**Runtime:** ~5–10 minutes (rate-limited to 0.15s between requests per SEC guidelines).

In [1]:
import sys
sys.path.insert(0, '..')

import os
import pandas as pd
from pathlib import Path

from src.config import COMPANIES, YEARS, RAW_DIR, PROCESSED_DIR
from src.sec_loader import load_all_filings, get_filing_metadata

print("Companies:", list(COMPANIES.keys()))
print("Years:", YEARS)
print(f"Expected filings: {len(COMPANIES) * len(YEARS)}")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/1y/42jcd32x74sfkj7xjlx937xm0000gn/T/ipykernel_13122/2686329417.py", line 5, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/1y/42jcd32x74sfkj7xjlx937xm0000gn/T/ipykernel_13122/2686329417.py", line 5, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/1y/42jcd32x74sfkj7xjlx937xm0000gn/T/ipykernel_13122/2686329417.py", line 5, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.9/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/1y/42jcd32x74sfkj7xjlx937xm0000gn/T/ipykernel_13122/2686329417.py", line 5, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.9/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

Companies: ['AAPL', 'MSFT', 'NVDA', 'TSLA', 'JPM']
Years: [2022, 2023, 2024]
Expected filings: 15

## 1.1 — Download all filings

This cell runs the full download pipeline. It will skip files that are already present on disk (idempotent). Progress is logged to stdout.

In [2]:
metadata_df = load_all_filings(save_dir=RAW_DIR)
metadata_df

Downloading filings:   0%|                                                           | 0/15 [00:00<?, ?it/s]

  Fetching metadata: AAPL 2022
  Downloading: AAPL 2022 (0000320193-22-000108)

Downloading filings:   7%|███▍                                               | 1/15 [00:01<00:23,  1.71s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/AAPL_2022_10K.txt
  Fetching metadata: AAPL 2023
  Downloading: AAPL 2023 (0000320193-23-000106)

Downloading filings:  13%|██████▊                                            | 2/15 [00:03<00:20,  1.55s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/AAPL_2023_10K.txt
  Fetching metadata: AAPL 2024
  Downloading: AAPL 2024 (0000320193-24-000123)

Downloading filings:  20%|██████████▏                                        | 3/15 [00:04<00:17,  1.48s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/AAPL_2024_10K.txt
  Fetching metadata: MSFT 2022
  Downloading: MSFT 2022 (0001564590-22-026876)

Downloading filings:  27%|█████████████▌                                     | 4/15 [00:07<00:24,  2.18s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/MSFT_2022_10K.txt
  Fetching metadata: MSFT 2023
  Downloading: MSFT 2023 (0000950170-23-035122)

Downloading filings:  33%|█████████████████                                  | 5/15 [00:11<00:26,  2.67s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/MSFT_2023_10K.txt
  Fetching metadata: MSFT 2024
  Downloading: MSFT 2024 (0000950170-24-087843)

Downloading filings:  40%|████████████████████▍                              | 6/15 [00:14<00:26,  2.92s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/MSFT_2024_10K.txt
  Fetching metadata: NVDA 2022
  Downloading: NVDA 2022 (0001045810-22-000036)

Downloading filings:  47%|███████████████████████▊                           | 7/15 [00:16<00:19,  2.48s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/NVDA_2022_10K.txt
  Fetching metadata: NVDA 2023
  Downloading: NVDA 2023 (0001045810-23-000017)

Downloading filings:  53%|███████████████████████████▏                       | 8/15 [00:17<00:15,  2.21s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/NVDA_2023_10K.txt
  Fetching metadata: NVDA 2024
  Downloading: NVDA 2024 (0001045810-24-000029)

Downloading filings:  60%|██████████████████████████████▌                    | 9/15 [00:19<00:12,  2.15s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/NVDA_2024_10K.txt
  Fetching metadata: TSLA 2022
  Downloading: TSLA 2022 (0000950170-23-001409)

Downloading filings:  67%|█████████████████████████████████▎                | 10/15 [00:32<00:27,  5.41s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/TSLA_2022_10K.txt
  Fetching metadata: TSLA 2023
  Downloading: TSLA 2023 (0001628280-24-002390)

Downloading filings:  73%|████████████████████████████████████▋             | 11/15 [00:34<00:17,  4.32s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/TSLA_2023_10K.txt
  Fetching metadata: TSLA 2024
  Downloading: TSLA 2024 (0001628280-25-003063)

Downloading filings:  80%|████████████████████████████████████████          | 12/15 [00:36<00:10,  3.57s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/TSLA_2024_10K.txt
  Fetching metadata: JPM 2022
  Downloading: JPM 2022 (0000019617-23-000231)

Downloading filings:  87%|███████████████████████████████████████████▎      | 13/15 [00:48<00:12,  6.22s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/JPM_2022_10K.txt
  Fetching metadata: JPM 2023
  Downloading: JPM 2023 (0000019617-24-000225)

Downloading filings:  93%|██████████████████████████████████████████████▋   | 14/15 [00:57<00:07,  7.06s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/JPM_2023_10K.txt
  Fetching metadata: JPM 2024
  Downloading: JPM 2024 (0000019617-25-000270)

Downloading filings: 100%|██████████████████████████████████████████████████| 15/15 [01:06<00:00,  4.41s/it]

  Saved: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/JPM_2024_10K.txt

Metadata saved to /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/processed/filing_metadata.csv

,ticker,cik,company,year,filing_type,accession_number,filing_date,report_date,primary_document,local_path
0,AAPL,0000320193,Apple Inc.,2022,10-K,0000320193-22-000108,2022-10-28,2022-09-24,aapl-20220924.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
1,AAPL,0000320193,Apple Inc.,2023,10-K,0000320193-23-000106,2023-11-03,2023-09-30,aapl-20230930.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
2,AAPL,0000320193,Apple Inc.,2024,10-K,0000320193-24-000123,2024-11-01,2024-09-28,aapl-20240928.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
3,MSFT,0000789019,MICROSOFT CORP,2022,10-K,0001564590-22-026876,2022-07-28,2022-06-30,msft-10k_20220630.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
4,MSFT,0000789019,MICROSOFT CORP,2023,10-K,0000950170-23-035122,2023-07-27,2023-06-30,msft-20230630.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
5,MSFT,0000789019,MICROSOFT CORP,2024,10-K,0000950170-24-087843,2024-07-30,2024-06-30,msft-20240630.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
6,NVDA,0001045810,NVIDIA CORP,2022,10-K,0001045810-22-000036,2022-03-18,2022-01-30,nvda-20220130.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
7,NVDA,0001045810,NVIDIA CORP,2023,10-K,0001045810-23-000017,2023-02-24,2023-01-29,nvda-20230129.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
8,NVDA,0001045810,NVIDIA CORP,2024,10-K,0001045810-24-000029,2024-02-21,2024-01-28,nvda-20240128.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
9,TSLA,0001318605,"Tesla, Inc.",2022,10-K,0000950170-23-001409,2023-01-31,2022-12-31,tsla-20221231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
10,TSLA,0001318605,"Tesla, Inc.",2023,10-K,0001628280-24-002390,2024-01-29,2023-12-31,tsla-20231231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
11,TSLA,0001318605,"Tesla, Inc.",2024,10-K,0001628280-25-003063,2025-01-30,2024-12-31,tsla-20241231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
12,JPM,0000019617,JPMORGAN CHASE & CO,2022,10-K,0000019617-23-000231,2023-02-21,2022-12-31,jpm-20221231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
13,JPM,0000019617,JPMORGAN CHASE & CO,2023,10-K,0000019617-24-000225,2024-02-16,2023-12-31,jpm-20231231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...
14,JPM,0000019617,JPMORGAN CHASE & CO,2024,10-K,0000019617-25-000270,2025-02-14,2024-12-31,jpm-20241231.htm,/Users/xieweixun/Desktop/projects/sec-rag-fail...

## 1.2 — Inspect the metadata table

Check that we have a row for each company × year, verify accession numbers, and identify any download failures.

In [3]:
print(f"Total filings attempted: {len(metadata_df)}")
print(f"Successful downloads: {metadata_df['local_path'].notna().sum()}")
print(f"Failures: {metadata_df['local_path'].isna().sum()}")

# Show the pivot table: company × year
pivot = metadata_df.pivot_table(
    index='ticker',
    columns='year',
    values='filing_date',
    aggfunc='first'
)
print("\nFiling dates by company × year:")
pivot

Total filings attempted: 15
Successful downloads: 15
Failures: 0

Filing dates by company × year:

year          2022        2023        2024
ticker
AAPL    2022-10-28  2023-11-03  2024-11-01
JPM     2023-02-21  2024-02-16  2025-02-14
MSFT    2022-07-28  2023-07-27  2024-07-30
NVDA    2022-03-18  2023-02-24  2024-02-21
TSLA    2023-01-31  2024-01-29  2025-01-30

In [4]:
# Check for any rows that failed
failures = metadata_df[metadata_df['local_path'].isna()]
if len(failures) > 0:
    print("Failed downloads:")
    print(failures[['ticker', 'year', 'error']])
else:
    print("All filings downloaded successfully.")

All filings downloaded successfully.

## 1.3 — Spot-check one filing

Load NVDA 2024 and print the first 3000 characters to verify the HTML was stripped and the text is readable.

In [5]:
spot_check = metadata_df[(metadata_df['ticker'] == 'NVDA') & (metadata_df['year'] == 2024)]
if len(spot_check) > 0 and spot_check.iloc[0]['local_path']:
    path = spot_check.iloc[0]['local_path']
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    print(f"File: {path}")
    print(f"Total characters: {len(text):,}")
    print(f"Total lines: {text.count(chr(10)):,}")
    print("\n--- First 3000 characters ---")
    print(text[:3000])
else:
    print("NVDA 2024 not available for spot check.")

File: /Users/xieweixun/Desktop/projects/sec-rag-failure-modes/notebooks/../src/../data/raw/NVDA_2024_10K.txt
Total characters: 358,853
Total lines: 6,263

--- First 3000 characters ---
nvda-20240128
0001045810
2024
FY
false
350
P3Y
P4Y
P5Y
P1Y
P3Y
P3Y
P1Y
http://fasb.org/us-gaap/2023#AccruedLiabilitiesCurrent
http://fasb.org/us-gaap/2023#AccruedLiabilitiesCurrent
http://fasb.org/us-gaap/2023#AccruedLiabilitiesCurrent
0001045810
2023-01-30
2024-01-28
0001045810
2023-07-28
iso4217:USD
0001045810
2024-02-16
xbrli:shares
0001045810
nvda:JohnO.DabiriMember
2023-10-30
2024-01-28
0001045810
2023-10-30
2024-01-28
0001045810
nvda:JohnO.DabiriMember
2024-01-28
0001045810
2022-01-31
2023-01-29
0001045810
2021-02-01
2022-01-30
iso4217:USD
xbrli:shares
0001045810
2024-01-28
0001045810
2023-01-29
0001045810
us-gaap:CommonStockMember
2021-01-31
0001045810
us-gaap:AdditionalPaidInCapitalMember
2021-01-31
0001045810
us-gaap:TreasuryStockCommonMember
2021-01-31
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2021-01-31
0001045810
us-gaap:RetainedEarningsMember
2021-01-31
0001045810
2021-01-31
0001045810
us-gaap:RetainedEarningsMember
2021-02-01
2022-01-30
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2021-02-01
2022-01-30
0001045810
us-gaap:CommonStockMember
2021-02-01
2022-01-30
0001045810
us-gaap:AdditionalPaidInCapitalMember
2021-02-01
2022-01-30
0001045810
us-gaap:TreasuryStockCommonMember
2021-02-01
2022-01-30
0001045810
us-gaap:CommonStockMember
2022-01-30
0001045810
us-gaap:AdditionalPaidInCapitalMember
2022-01-30
0001045810
us-gaap:TreasuryStockCommonMember
2022-01-30
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2022-01-30
0001045810
us-gaap:RetainedEarningsMember
2022-01-30
0001045810
2022-01-30
0001045810
us-gaap:RetainedEarningsMember
2022-01-31
2023-01-29
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2022-01-31
2023-01-29
0001045810
us-gaap:CommonStockMember
2022-01-31
2023-01-29
0001045810
us-gaap:AdditionalPaidInCapitalMember
2022-01-31
2023-01-29
0001045810
us-gaap:CommonStockMember
2023-01-29
0001045810
us-gaap:AdditionalPaidInCapitalMember
2023-01-29
0001045810
us-gaap:TreasuryStockCommonMember
2023-01-29
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2023-01-29
0001045810
us-gaap:RetainedEarningsMember
2023-01-29
0001045810
us-gaap:RetainedEarningsMember
2023-01-30
2024-01-28
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2023-01-30
2024-01-28
0001045810
us-gaap:CommonStockMember
2023-01-30
2024-01-28
0001045810
us-gaap:AdditionalPaidInCapitalMember
2023-01-30
2024-01-28
0001045810
us-gaap:CommonStockMember
2024-01-28
0001045810
us-gaap:AdditionalPaidInCapitalMember
2024-01-28
0001045810
us-gaap:TreasuryStockCommonMember
2024-01-28
0001045810
us-gaap:AccumulatedOtherComprehensiveIncomeMember
2024-01-28
0001045810
us-gaap:RetainedEarningsMember
2024-01-28
0001045810
nvda:ServerStorageAndNetworkEquipmentMember
2023-01-31
0001045810
nvda:ServerStorageAndNetworkEquipmentMember
srt:MinimumMember
2023-02-28
0001045810
srt:MaximumMember
nvda:ServerStorageAndNetworkEquipmentMember
2023-02-28
0001045810
nvda:AssemblingAndTestingEquipmentMember
srt:Min

## 1.4 — File size summary

Compare file sizes to verify we downloaded substantive content (10-K filings are typically 300KB–2MB of plain text).

In [6]:
import os

size_records = []
for _, row in metadata_df[metadata_df['local_path'].notna()].iterrows():
    path = row['local_path']
    if os.path.exists(path):
        size_kb = os.path.getsize(path) / 1024
        size_records.append({
            'ticker': row['ticker'],
            'year': row['year'],
            'size_kb': round(size_kb, 1)
        })

size_df = pd.DataFrame(size_records)
print(size_df.pivot_table(index='ticker', columns='year', values='size_kb', aggfunc='first'))

year      2022    2023    2024
ticker
AAPL     229.7   213.4   215.4
JPM     1352.2  1443.3  1415.9
MSFT     371.5   366.1   382.6
NVDA     319.1   332.6   351.7
TSLA     435.2   420.0   407.4